# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# Home Assistant Community Store
hacs:
  token: !secret hacs_token

# DuckDNS
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Google Calendar
google:
  client_id: !secret google_client_id_calendar
  client_secret: !secret google_client_secret_calendar

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Alexa
# https://www.nabucasa.com/config/amazon_alexa/
#cloud:
#  alexa:
#    entity_config:
#      switch.yamaha_receiver:
#        display_categories: MUSIC_SYSTEM
#      switch.bettlicht:
#        display_categories: LIGHT

# Wohnzimmer Stehlampe (L510 Tapo)
light:
    platform: tapo_p100_control
    ip_address: 192.168.178.22
    email: !secret tapo_email
    password: !secret tapo_password

alexa:
  smart_home:
    filter:
      include_entities:
        - cover.rollo
        - vacuum.robbi
        - climate.daniels_zimmer
      include_domains:
        - light
        - switch
      exclude_domains:
        - binary_sensor
        - calendar
        - sensor
        - zone
        - device_tracker
        - weather
        - script
        - sun

media_player:
  # Use the Python ADB implementation
  - platform: androidtv
    name: firestick
    host: 192.168.178.85
    adb_server_ip: 127.0.0.1
    device_class: firetv
    adb_server_port: 5037
